pr
SergeyGushan/gophermart pull request #1
Opened 2024-02-22 00:08 UTC by SergeyGushan

2024-02-22 08:18 UTC, maxlyaptsev requested changes

2024-02-22 08:18 UTC, maxlyaptsev commented on internal/adapter/pgsqlrepo/transactor.go
> +package pgsqlrepo
лучше в отдельный пакет убрать

2024-02-22 08:18 UTC, maxlyaptsev commented on internal/handler/http/api/router.go
> +}
не уверен что имеет смысл роутер на две составляющие разделять

2024-02-22 08:18 UTC, maxlyaptsev commented on internal/service/luhn.go
> +package service
для единообразия лучше тоже в пакет положить - чтобы все сервисы лежали в пакетах

2024-02-22 08:18 UTC, maxlyaptsev commented on internal/handler/http/api/create_order.go
> +	_, saveOrderError := h.uc.CreateOrder(ctx, orderID, userID)
В чем суть юзкейсов - это не какие-то маленькие функции. Они выполняют большую бизнес-задачу.
В этом случае юзкейс должен проверить по луну, получить пользователя, создать заказ.
При этом сам юзкейс может использовать несколько сервисов

2024-02-22 08:18 UTC, maxlyaptsev commented on internal/handler/http/api/create_order.go
> +	go h.uc.Accrual(ctx, orderID, userID)
Горутины не должны создаваться в ручке
- при сбое потеряем заказ и никогда больше не сможем его обработать
- в случае долгого ответа accrual будет скапливаться большое количество ожидающих горутин
- при запуске нескольких экземпляров приложения не сможем обрабатывать "чужие заказы"
- нет рейтлимита и размазывания нагрузки по времени

2024-02-22 08:18 UTC, maxlyaptsev commented on internal/handler/http/api/login.go
> +	}
юзкейс - залогинить пользователя. Получение пользователя в данном случае это просто сервисное действие

2024-02-22 08:18 UTC, maxlyaptsev commented on internal/handler/http/api/balance_withdraw.go
> +	)
это все юзкейс "снятие с баланса", и он состоит из:
- проверить по луну
- получить пользователя
- получить баланс
- проверить баланс
- добавить операцию снятие

2024-02-22 08:24 UTC, SergeyGushan commented on internal/handler/http/api/router.go
> +}
у них разные мидлвары

2024-02-22 21:28 UTC, SergeyGushan commented on internal/handler/http/api/login.go
> +	}
передавать w http.ResponseWriter в юзкеййс?

2024-02-26 14:54 UTC, maxlyaptsev commented on internal/handler/http/api/create_order.go
> +	go h.uc.Accrual(ctx, orderID, userID)
Актуально. В курсе была разобрана тема с воркерами. Это как раз идеальный кейс чтобы ими воспользоваться

2024-02-29 09:09 UTC, maxlyaptsev commented on internal/usecase/accrual.go
> +		return
пропущено логирование

2024-02-29 16:04 UTC, maxlyaptsev commented on worker/accrual.go
> +		log.Fatal(err)
log.fatal не стоит использовать - он вызывает панику.  А панику не принято в коде использовать

2024-02-29 16:06 UTC, maxlyaptsev commented on worker/worker.go
> +package worker
лишний файл похоже

2024-03-01 14:51 UTC, merged